### ISSUE TITLE
Update DynamicSupervisor instead of simple_one_for_one strategy

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealelixir/website#90]
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.11.2) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.11.2) lib/supervisor.ex:556: Supervisor.start_link/2
  (phoenix 1.4.2) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.13.2) supervisor.erl:385: :supervisor.do_start_child_i/3
  (stdlib 3.13.2) supervisor.erl:371: :supervisor.do_start_child/2
  (stdlib 3.13.2) supervisor.erl:355: anonymous fn/3 in :supervisor.start_children/2

**Comment by nicholasjhenry** [comment]
Resolved in #92
